#pragma once

#ifndef GAME_DATA_DIRECTORY
#define GAME_DATA_DIRECTORY "Data"
#endif

#define USER_DATA_FILE GAME_DATA_DIRECTORY "/user.dat"
#define SCORES_DATA_FILE GAME_DATA_DIRECTORY "/scores.dat"
#define SAVES_DATA_FILE GAME_DATA_DIRECTORY "/saves.dat"
#define HISTORY_DATA_FILE GAME_DATA_DIRECTORY "/history.dat"
#define LOG_DATA_FILE GAME_DATA_DIRECTORY "/app.log"

#define USER_PASSWORD_LENGTH_MAX 21
#define USER_PASSWORD_LENGTH_MIN 6
#define USER_NAME_LENGTH_MAX 32
#define USER_NAME_LENGTH_MIN 2

#define RANK_ENTRIES_MAX 256
#define RANK_TOP_COUNT 10
#define INPUT_BUFFER_LENGTH 128
#define GAME_NEW_TILE_TWO_PERCENT 90
#define SAVE_ENTRIES_MAX 256
#define HISTORY_ENTRIES_MAX 512
#define GAME_MODE_ID_LENGTH 32
#define LOG_FILE_MAX_BYTES (1024 * 1024)
#define USERNAME_CHANGE_COOLDOWN_HOURS 72
#define USERNAME_CHANGE_COOLDOWN_SECONDS (USERNAME_CHANGE_COOLDOWN_HOURS * 60 * 60)

#define HASH_BASE1 131u
#define HASH_BASE2 13331u
#define HASH_MOD1 1000000007u
#define HASH_MOD2 1000000009u
